[package]
name = "file"
version = "0.1.0"
authors = ["icew4ll <icew4ll@tuta.io>"]

[dependencies]
csv = "1.0.0"
serde_derive = "1.0.70"
serde = "1.0.70"
clap = "2.32.0"
dotenv_codegen = "0.11.0"
envy = "0.3.2"
dotenv = "0.13.0"
duct = "0.11.0"
